
import json
import os


entrypoint_information = {
    'backdrop.collector.ga': {
        'service': 'services/ga.json',
        'repeat': 'daily',
    },
    'backdrop.collector.ga.trending': {
        'service': 'services/ga.json',
        'repeat': 'daily',
    },
    'backdrop.collector.ga.contrib.content.table': {
        'service': 'services/ga.json',
        'repeat': 'daily',
    },
    'backdrop.collector.ga.realtime': {
        'service': 'services/ga-realtime.json',
        'repeat': '2minute',
    },
    'backdrop.collector.pingdom': {
        'service': 'services/pingdom.json',
        'repeat': 'hourly',
    },
}


def daily(jobs):
    entries = ['#', '# Daily jobs', '#', '']
    for index, (query, service) in enumerate(jobs):
        hour, minute = divmod(index, 60)
        entries.append('{0} {1} * * *,{2},{3}'.format(minute, hour, query, service))
    return entries


def hourly(jobs):
    entries = ['#', '# Hourly jobs', '#', '']
    for index, (query, service) in enumerate(jobs):
        minute = index % 60
        entries.append('{0} * * * *,{1},{2}'.format(minute, query, service))
    return entries


def two_minute(jobs):
    entries = ['#', '# Run every two minutes', '#', '']
    for index, (query, service) in enumerate(jobs):
        entries.append('1-59/2 * * * *,{0},{1}'.format(query, service))
    return entries


def main():
    queries = [os.path.join(dp, f) for dp, dn, filenames in os.walk('queries') for f in filenames if os.path.splitext(f)[1] == '.json']
    time_buckets = {}

    for query in queries:
        with open(query) as query_fd:
            entrypoint = json.load(query_fd)['entrypoint']

        query_info = entrypoint_information.get(entrypoint, None)

        if query_info is None:
            print "No entrypoint {0} from {1}".format(entrypoint, query)
        else:
            if query_info['repeat'] not in time_buckets:
                time_buckets[query_info['repeat']] = []

            time_buckets[query_info['repeat']].append((query, query_info['service']))

    daily_jobs = daily(time_buckets['daily'])
    hourly_jobs = hourly(time_buckets['hourly'])
    two_minute_jobs = two_minute(time_buckets['2minute'])

    spacer = ['', '']
    cronjobs_content = [
        '#',
        '# This file was generated by cronjobs.py',
        '#',
    ] + spacer + daily_jobs + spacer + hourly_jobs + spacer + two_minute_jobs

    print '\n'.join(cronjobs_content)




if __name__ == '__main__':
    main()
